[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix=../.. --workspaces=false --ignore-scripts",
  "cd ../.. && npm install"
]

[phases.build]
cmds = [
  "npx prisma generate --schema=../../packages/database/prisma/schema.prisma",
  "npx nest build"
]

[start]
cmd = "node dist/main"
